import os

# Secrets (in GitHub Actions)
LAT = float(os.environ["START_LAT"])
LON = float(os.environ["START_LON"])

TIMEZONE = os.environ["TIMEZONE"]

NTFY_TOPIC = os.environ.get("NTFY_TOPIC", "BIKEWEATHER_0183")
NTFY_URL = f"https://ntfy.sh/{NTFY_TOPIC}"

NTFY_LUFTEN_TOPIC = os.environ.get("NTFY_LUFTEN_TOPIC", "LUEFTENWEATHER_0183")
NTFY_LUFTEN_URL = f"https://ntfy.sh/{NTFY_LUFTEN_TOPIC}" if NTFY_LUFTEN_TOPIC else None

# Public config (safe to commit)
START_HOUR = 7
END_HOUR = 20

MAX_RAIN_MM = 0.5
MAX_POP = 40


# Notification tuning
POP_DELTA_NOTIFY = 5          # percentage points
RAIN_DELTA_NOTIFY = 0.5       # mm
NOTIFY_ON_STATUS_CHANGE = True

WEATHER_REPORT_START_HOUR = 8
WEATHER_REPORT_END_HOUR = 17
WEATHER_REPORT_NOTIFY_HOUR = 20

HOT_HIGH_TEMP_F_THRESHOLD = 88.0
HOT_COOL_TEMP_F_THRESHOLD = 77.0

# Backward-compatible aliases for the earlier Lüften naming
LUFTEN_HIGH_TEMP_F_THRESHOLD = HOT_HIGH_TEMP_F_THRESHOLD
LUFTEN_COOL_TEMP_F_THRESHOLD = HOT_COOL_TEMP_F_THRESHOLD
LUFTEN_EVENING_NOTIFY_HOUR = WEATHER_REPORT_NOTIFY_HOUR

STATE_FILE = f"state_{NTFY_TOPIC}.json"
